name: Web PrivRent(Inside)2

on:
  workflow_run:
    workflows: ["Web PrivRent(Inside)"]
    types:
      - completed

jobs:
  followupjob2:
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ vars.BASE_URL }}
      CON_STR: ${{ vars.CON_STR }}
      LOG_TRG: ${{ vars.LOG_STR }}
      CON_STR_COMS: ${{ vars.CON_STR_COMS }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install other dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools==57.5.0
          
      - name: Install dependencies from requirements.txt
        run: |
          python -m pip install -r requirements.txt
          # If you want to avoid using the 2to3 tool, ensure that your dependencies are Python 3 compatible.

      - name: Run web scraping
        run: |
          python PrivateRentals_Inside2.py 
