name: Airtest

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
jobs:
  tester:
    runs-on: ubuntu-latest
    env:
      SECRET_STR: ${{ vars.T_STR }}  # Pass the secret to the environment
      LOG_TRG: ${{ vars.LOG_TRG }}

    steps:
      - name: Debug LOG_TRG
        run: echo "LOG_TRG=$LOG_TRG"
